set(CPACK_PACKAGE_NAME "labstreaminglayer")
set(CPACK_PACKAGE_VERSION_MAJOR ${LSL_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${LSL_VERSION_MINOR})
set(SYSTEM_PROCESSOR ${CMAKE_SYSTEM_PROCESSOR})
