# this file doesn't get installed, it's just here to prevent one type of
# build configuration error
# the LSLConfig.cmake in the installed tree gets generated by the export
# settings in LSL/liblsl/CMakeLists.txt

message(FATAL_ERROR "You set LSL_ROOT to the labstreaminglayer root directory
instead of an install tree.
Please consult the 'Build instructions' part in 'INSTALL.md' to decide if you
want to do an out of tree build (and set LSL_ROOT to a built LSL path) or
unset LSL_ROOT and call CMake from the root directory to build LSL and some
additional apps")
