set(CPACK_GENERATOR DEB)
set(CPACK_SET_DESTDIR 1)
set(CPACK_INSTALL_PREFIX "/usr")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Tristan Stenner <ttstenner@gmail.com>")
set(CPACK_DEBIAN_ENABLE_COMPONENT_DEPENDS 1)
set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_DEBIAN_PACKAGE_PRIORITY optional)

# include distribution name (e.g. trusty or xenial) in the file name
# only works on CMake>=3.6, does nothing on CMake<3.6
find_program(LSB_RELEASE lsb_release)
execute_process(COMMAND ${LSB_RELEASE} -cs
	OUTPUT_VARIABLE LSB_RELEASE_CODENAME
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_RELEASE ${LSB_RELEASE_CODENAME})

